raw_data_config: 
  raw_data_csv: data/raw/data.csv
  model_var: ['A','B','C','D','E','F','Target']
  train_test_split_ratio: 0.2
  target: Target 
  random_state: 111
  new_train_data_csv: data/raw/train.csv

processed_data_config:
  train_data_csv: data/processed/train.csv
  test_data_csv:  data/processed/test.csv

model_choice:
  # random_forest or knn
  model: 'knn'
  # model: 'random_forest'

random_forest: 
  max_depth: 10
  n_estimators: 50

knn: 
  n_neighbors: 5

mlflow_global_config:
  artifacts_dir: artifacts
  experiment_name: model_iris
  registered_model_name: iris_model
  remote_server_uri: http://localhost:1234

mlflow_random_forest_config:
  run_name: random_forest
  

mlflow_knn_config:
  run_name: knn
  
model_dir: models/model.joblib

model_webapp_dir: webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: Target
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html